version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Developer
